allowBuilds:
  '@heroui-pro/react': true
  heroui-native-pro: true
  heroui-pro: true

minimumReleaseAgeExclude:
  - lucide-react@1.26.0

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp

ignoredBuiltDependencies:
  - '@zowe/secrets-for-zowe-sdk'
  - unrs-resolver
