-- Cuatro ejercicios que tenian el nombre en ingles y unas instrucciones genericas
-- que no describian lo que muestra su imagen. Se identifican por su codigo.
--
-- El texto de busqueda (searchName) lleva el nombre al comienzo y las
-- instrucciones adentro: se reemplazan las dos partes.
--
-- La copia de cada entrenador se actualiza solo en lo que no cambio: el nombre
-- si conserva el original, y las instrucciones si conserva las originales.

-- 3292: Elevator -> Elevador invertido en anillas
UPDATE "ExerciseCoach" SET "searchName" = replace( "searchName", 'ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. coloca las manos sobre las caderas o cruzalas frente al pecho. manteniendo la espalda recta, inclinate lentamente hacia adelante desde la cintura, bajando la parte superior del cuerpo hacia el suelo. haz una pausa por un momento en la posicion mas baja, luego sube lentamente la parte superior del cuerpo de vuelta a la posicion inicial. repite el numero de repeticiones deseado.', 'cuelgate de las anillas y lleva el cuerpo a la posicion invertida: cabeza hacia abajo, piernas extendidas hacia arriba y el cuerpo en linea recta. desde ahi, flexiona los brazos para subir el cuerpo en linea recta, acercando la cadera a las anillas. baja de forma controlada hasta extender los brazos, sin perder la linea del cuerpo ni balancearte. repite el numero de repeticiones deseado.' ), "instructions" = 'Cuélgate de las anillas y lleva el cuerpo a la posición invertida: cabeza hacia abajo, piernas extendidas hacia arriba y el cuerpo en línea recta. Desde ahí, flexiona los brazos para subir el cuerpo en línea recta, acercando la cadera a las anillas. Baja de forma controlada hasta extender los brazos, sin perder la línea del cuerpo ni balancearte. Repite el número de repeticiones deseado.'
WHERE "instructions" = 'Ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. Coloca las manos sobre las caderas o crúzalas frente al pecho. Manteniendo la espalda recta, inclínate lentamente hacia adelante desde la cintura, bajando la parte superior del cuerpo hacia el suelo. Haz una pausa por un momento en la posición más baja, luego sube lentamente la parte superior del cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '3292' );
UPDATE "ExerciseCoach" SET "tips" = 'Cuélgate de las anillas y lleva el cuerpo a la posición invertida: cabeza hacia abajo, piernas extendidas hacia arriba y el cuerpo en línea recta. Desde ahí, flexiona los brazos para subir el cuerpo en línea recta, acercando la cadera a las anillas. Baja de forma controlada hasta extender los brazos, sin perder la línea del cuerpo ni balancearte. Repite el número de repeticiones deseado.'
WHERE "tips" = 'Ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. Coloca las manos sobre las caderas o crúzalas frente al pecho. Manteniendo la espalda recta, inclínate lentamente hacia adelante desde la cintura, bajando la parte superior del cuerpo hacia el suelo. Haz una pausa por un momento en la posición más baja, luego sube lentamente la parte superior del cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '3292' );
UPDATE "ExerciseCoach" SET "name" = 'Elevador invertido en anillas', "searchName" = CASE WHEN "searchName" LIKE 'elevator%' THEN 'elevador invertido en anillas' || substr( "searchName", 9 ) ELSE "searchName" END
WHERE "name" = 'Elevator' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '3292' );
UPDATE "ExerciseGlobal" SET "name" = 'Elevador invertido en anillas', "instructions" = 'Cuélgate de las anillas y lleva el cuerpo a la posición invertida: cabeza hacia abajo, piernas extendidas hacia arriba y el cuerpo en línea recta. Desde ahí, flexiona los brazos para subir el cuerpo en línea recta, acercando la cadera a las anillas. Baja de forma controlada hasta extender los brazos, sin perder la línea del cuerpo ni balancearte. Repite el número de repeticiones deseado.', "searchName" = replace( CASE WHEN "searchName" LIKE 'elevator%' THEN 'elevador invertido en anillas' || substr( "searchName", 9 ) ELSE "searchName" END, 'ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. coloca las manos sobre las caderas o cruzalas frente al pecho. manteniendo la espalda recta, inclinate lentamente hacia adelante desde la cintura, bajando la parte superior del cuerpo hacia el suelo. haz una pausa por un momento en la posicion mas baja, luego sube lentamente la parte superior del cuerpo de vuelta a la posicion inicial. repite el numero de repeticiones deseado.', 'cuelgate de las anillas y lleva el cuerpo a la posicion invertida: cabeza hacia abajo, piernas extendidas hacia arriba y el cuerpo en linea recta. desde ahi, flexiona los brazos para subir el cuerpo en linea recta, acercando la cadera a las anillas. baja de forma controlada hasta extender los brazos, sin perder la linea del cuerpo ni balancearte. repite el numero de repeticiones deseado.' )
WHERE "externalId" = '3292' AND "name" = 'Elevator';

-- 0777: Spell caster -> Rotación de tronco con mancuernas (spell caster)
UPDATE "ExerciseCoach" SET "searchName" = replace( "searchName", 'ponte de pie con los pies separados a la altura de los hombros y sujeta una mancuerna con una mano. flexiona ligeramente las rodillas e inclinate hacia adelante desde la cintura, manteniendo la espalda recta. extiende el brazo con la mancuerna hacia el pie opuesto, rotando el torso mientras lo haces. regresa a la posicion inicial y repite del otro lado. continua alternando lados durante el numero de repeticiones deseado.', 'ponte de pie con los pies separados a la altura de los hombros y una mancuerna en cada mano. flexiona ligeramente las rodillas y gira el tronco hacia un lado, llevando las dos mancuernas junto a esa cadera. desde ahi, gira el tronco hacia el otro lado mientras llevas las mancuernas por delante del cuerpo hasta la altura de los hombros, con los brazos casi extendidos. baja las mancuernas de forma controlada hasta la otra cadera y repite el movimiento hacia el lado contrario. manten el abdomen activo y la espalda recta durante todo el recorrido.' ), "instructions" = 'Ponte de pie con los pies separados a la altura de los hombros y una mancuerna en cada mano. Flexiona ligeramente las rodillas y gira el tronco hacia un lado, llevando las dos mancuernas junto a esa cadera. Desde ahí, gira el tronco hacia el otro lado mientras llevas las mancuernas por delante del cuerpo hasta la altura de los hombros, con los brazos casi extendidos. Baja las mancuernas de forma controlada hasta la otra cadera y repite el movimiento hacia el lado contrario. Mantén el abdomen activo y la espalda recta durante todo el recorrido.'
WHERE "instructions" = 'Ponte de pie con los pies separados a la altura de los hombros y sujeta una mancuerna con una mano. Flexiona ligeramente las rodillas e inclínate hacia adelante desde la cintura, manteniendo la espalda recta. Extiende el brazo con la mancuerna hacia el pie opuesto, rotando el torso mientras lo haces. Regresa a la posición inicial y repite del otro lado. Continúa alternando lados durante el número de repeticiones deseado.' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0777' );
UPDATE "ExerciseCoach" SET "tips" = 'Ponte de pie con los pies separados a la altura de los hombros y una mancuerna en cada mano. Flexiona ligeramente las rodillas y gira el tronco hacia un lado, llevando las dos mancuernas junto a esa cadera. Desde ahí, gira el tronco hacia el otro lado mientras llevas las mancuernas por delante del cuerpo hasta la altura de los hombros, con los brazos casi extendidos. Baja las mancuernas de forma controlada hasta la otra cadera y repite el movimiento hacia el lado contrario. Mantén el abdomen activo y la espalda recta durante todo el recorrido.'
WHERE "tips" = 'Ponte de pie con los pies separados a la altura de los hombros y sujeta una mancuerna con una mano. Flexiona ligeramente las rodillas e inclínate hacia adelante desde la cintura, manteniendo la espalda recta. Extiende el brazo con la mancuerna hacia el pie opuesto, rotando el torso mientras lo haces. Regresa a la posición inicial y repite del otro lado. Continúa alternando lados durante el número de repeticiones deseado.' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0777' );
UPDATE "ExerciseCoach" SET "name" = 'Rotación de tronco con mancuernas (spell caster)', "searchName" = CASE WHEN "searchName" LIKE 'spell caster%' THEN 'rotacion de tronco con mancuernas (spell caster)' || substr( "searchName", 13 ) ELSE "searchName" END
WHERE "name" = 'Spell caster' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0777' );
UPDATE "ExerciseGlobal" SET "name" = 'Rotación de tronco con mancuernas (spell caster)', "instructions" = 'Ponte de pie con los pies separados a la altura de los hombros y una mancuerna en cada mano. Flexiona ligeramente las rodillas y gira el tronco hacia un lado, llevando las dos mancuernas junto a esa cadera. Desde ahí, gira el tronco hacia el otro lado mientras llevas las mancuernas por delante del cuerpo hasta la altura de los hombros, con los brazos casi extendidos. Baja las mancuernas de forma controlada hasta la otra cadera y repite el movimiento hacia el lado contrario. Mantén el abdomen activo y la espalda recta durante todo el recorrido.', "searchName" = replace( CASE WHEN "searchName" LIKE 'spell caster%' THEN 'rotacion de tronco con mancuernas (spell caster)' || substr( "searchName", 13 ) ELSE "searchName" END, 'ponte de pie con los pies separados a la altura de los hombros y sujeta una mancuerna con una mano. flexiona ligeramente las rodillas e inclinate hacia adelante desde la cintura, manteniendo la espalda recta. extiende el brazo con la mancuerna hacia el pie opuesto, rotando el torso mientras lo haces. regresa a la posicion inicial y repite del otro lado. continua alternando lados durante el numero de repeticiones deseado.', 'ponte de pie con los pies separados a la altura de los hombros y una mancuerna en cada mano. flexiona ligeramente las rodillas y gira el tronco hacia un lado, llevando las dos mancuernas junto a esa cadera. desde ahi, gira el tronco hacia el otro lado mientras llevas las mancuernas por delante del cuerpo hasta la altura de los hombros, con los brazos casi extendidos. baja las mancuernas de forma controlada hasta la otra cadera y repite el movimiento hacia el lado contrario. manten el abdomen activo y la espalda recta durante todo el recorrido.' )
WHERE "externalId" = '0777' AND "name" = 'Spell caster';

-- 0260: Cocoons -> Abdominal en capullo
UPDATE "ExerciseCoach" SET "searchName" = replace( "searchName", 'tumbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. coloca las manos detras de la cabeza con los codos apuntando hacia afuera. activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvandote hacia adelante hasta que tu torso forme un angulo de 45 grados. haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posicion inicial. repite el numero de repeticiones deseado.', 'tumbate boca arriba con las piernas extendidas y los brazos estirados por detras de la cabeza. activa el abdomen y, en un solo movimiento, lleva las rodillas hacia el pecho mientras levantas el torso y llevas los brazos hacia adelante, hasta abrazar las rodillas. haz una pausa breve en esa posicion cerrada. vuelve de forma controlada a la posicion inicial, extendiendo piernas y brazos sin apoyar del todo los pies en el suelo. repite el numero de repeticiones deseado.' ), "instructions" = 'Túmbate boca arriba con las piernas extendidas y los brazos estirados por detrás de la cabeza. Activa el abdomen y, en un solo movimiento, lleva las rodillas hacia el pecho mientras levantas el torso y llevas los brazos hacia adelante, hasta abrazar las rodillas. Haz una pausa breve en esa posición cerrada. Vuelve de forma controlada a la posición inicial, extendiendo piernas y brazos sin apoyar del todo los pies en el suelo. Repite el número de repeticiones deseado.'
WHERE "instructions" = 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Coloca las manos detrás de la cabeza con los codos apuntando hacia afuera. Activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvándote hacia adelante hasta que tu torso forme un ángulo de 45 grados. Haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0260' );
UPDATE "ExerciseCoach" SET "tips" = 'Túmbate boca arriba con las piernas extendidas y los brazos estirados por detrás de la cabeza. Activa el abdomen y, en un solo movimiento, lleva las rodillas hacia el pecho mientras levantas el torso y llevas los brazos hacia adelante, hasta abrazar las rodillas. Haz una pausa breve en esa posición cerrada. Vuelve de forma controlada a la posición inicial, extendiendo piernas y brazos sin apoyar del todo los pies en el suelo. Repite el número de repeticiones deseado.'
WHERE "tips" = 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Coloca las manos detrás de la cabeza con los codos apuntando hacia afuera. Activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvándote hacia adelante hasta que tu torso forme un ángulo de 45 grados. Haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0260' );
UPDATE "ExerciseCoach" SET "name" = 'Abdominal en capullo', "searchName" = CASE WHEN "searchName" LIKE 'cocoons%' THEN 'abdominal en capullo' || substr( "searchName", 8 ) ELSE "searchName" END
WHERE "name" = 'Cocoons' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0260' );
UPDATE "ExerciseGlobal" SET "name" = 'Abdominal en capullo', "instructions" = 'Túmbate boca arriba con las piernas extendidas y los brazos estirados por detrás de la cabeza. Activa el abdomen y, en un solo movimiento, lleva las rodillas hacia el pecho mientras levantas el torso y llevas los brazos hacia adelante, hasta abrazar las rodillas. Haz una pausa breve en esa posición cerrada. Vuelve de forma controlada a la posición inicial, extendiendo piernas y brazos sin apoyar del todo los pies en el suelo. Repite el número de repeticiones deseado.', "searchName" = replace( CASE WHEN "searchName" LIKE 'cocoons%' THEN 'abdominal en capullo' || substr( "searchName", 8 ) ELSE "searchName" END, 'tumbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. coloca las manos detras de la cabeza con los codos apuntando hacia afuera. activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvandote hacia adelante hasta que tu torso forme un angulo de 45 grados. haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posicion inicial. repite el numero de repeticiones deseado.', 'tumbate boca arriba con las piernas extendidas y los brazos estirados por detras de la cabeza. activa el abdomen y, en un solo movimiento, lleva las rodillas hacia el pecho mientras levantas el torso y llevas los brazos hacia adelante, hasta abrazar las rodillas. haz una pausa breve en esa posicion cerrada. vuelve de forma controlada a la posicion inicial, extendiendo piernas y brazos sin apoyar del todo los pies en el suelo. repite el numero de repeticiones deseado.' )
WHERE "externalId" = '0260' AND "name" = 'Cocoons';

-- 0641: Otis up -> Abdominal con disco sobre la cabeza (Otis up)
UPDATE "ExerciseCoach" SET "searchName" = replace( "searchName", 'tumbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. coloca las manos detras de la cabeza con los codos apuntando hacia afuera. activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvandote hacia adelante hasta que tu torso forme un angulo de 45 grados. haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posicion inicial. repite el numero de repeticiones deseado.', 'tumbate boca arriba con las rodillas flexionadas y los pies apoyados en el suelo. sujeta un disco con las dos manos sobre el pecho. activa el abdomen y levanta el torso hasta quedar sentado; al llegar arriba, empuja el disco por encima de la cabeza hasta extender los brazos. baja el disco de nuevo al pecho y desciende el torso de forma controlada hasta la posicion inicial. repite el numero de repeticiones deseado.' ), "instructions" = 'Túmbate boca arriba con las rodillas flexionadas y los pies apoyados en el suelo. Sujeta un disco con las dos manos sobre el pecho. Activa el abdomen y levanta el torso hasta quedar sentado; al llegar arriba, empuja el disco por encima de la cabeza hasta extender los brazos. Baja el disco de nuevo al pecho y desciende el torso de forma controlada hasta la posición inicial. Repite el número de repeticiones deseado.'
WHERE "instructions" = 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Coloca las manos detrás de la cabeza con los codos apuntando hacia afuera. Activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvándote hacia adelante hasta que tu torso forme un ángulo de 45 grados. Haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0641' );
UPDATE "ExerciseCoach" SET "tips" = 'Túmbate boca arriba con las rodillas flexionadas y los pies apoyados en el suelo. Sujeta un disco con las dos manos sobre el pecho. Activa el abdomen y levanta el torso hasta quedar sentado; al llegar arriba, empuja el disco por encima de la cabeza hasta extender los brazos. Baja el disco de nuevo al pecho y desciende el torso de forma controlada hasta la posición inicial. Repite el número de repeticiones deseado.'
WHERE "tips" = 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Coloca las manos detrás de la cabeza con los codos apuntando hacia afuera. Activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvándote hacia adelante hasta que tu torso forme un ángulo de 45 grados. Haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posición inicial. Repite el número de repeticiones deseado.' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0641' );
UPDATE "ExerciseCoach" SET "name" = 'Abdominal con disco sobre la cabeza (Otis up)', "searchName" = CASE WHEN "searchName" LIKE 'otis up%' THEN 'abdominal con disco sobre la cabeza (otis up)' || substr( "searchName", 8 ) ELSE "searchName" END
WHERE "name" = 'Otis up' AND "globalExerciseId" IN ( SELECT "id" FROM "ExerciseGlobal" WHERE "externalId" = '0641' );
UPDATE "ExerciseGlobal" SET "name" = 'Abdominal con disco sobre la cabeza (Otis up)', "instructions" = 'Túmbate boca arriba con las rodillas flexionadas y los pies apoyados en el suelo. Sujeta un disco con las dos manos sobre el pecho. Activa el abdomen y levanta el torso hasta quedar sentado; al llegar arriba, empuja el disco por encima de la cabeza hasta extender los brazos. Baja el disco de nuevo al pecho y desciende el torso de forma controlada hasta la posición inicial. Repite el número de repeticiones deseado.', "searchName" = replace( CASE WHEN "searchName" LIKE 'otis up%' THEN 'abdominal con disco sobre la cabeza (otis up)' || substr( "searchName", 8 ) ELSE "searchName" END, 'tumbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. coloca las manos detras de la cabeza con los codos apuntando hacia afuera. activando el abdomen, levanta lentamente la parte superior del cuerpo del suelo, curvandote hacia adelante hasta que tu torso forme un angulo de 45 grados. haz una pausa por un momento en la parte superior, luego baja lentamente la parte superior del cuerpo de vuelta a la posicion inicial. repite el numero de repeticiones deseado.', 'tumbate boca arriba con las rodillas flexionadas y los pies apoyados en el suelo. sujeta un disco con las dos manos sobre el pecho. activa el abdomen y levanta el torso hasta quedar sentado; al llegar arriba, empuja el disco por encima de la cabeza hasta extender los brazos. baja el disco de nuevo al pecho y desciende el torso de forma controlada hasta la posicion inicial. repite el numero de repeticiones deseado.' )
WHERE "externalId" = '0641' AND "name" = 'Otis up';
